### ISSUE TITLE
Maxcube (eQ-3 MAX!) is not showing temperatue if it is greater than 25.6 Celsius

### ISSUE THREAD

**Issue by davidhrbaty** [hackercowboy/python-maxcube-api#19]
Hello,
I have configured max cube with wall thermostats and radiator valves, everything is working, but nowadays is too hot inside my house and I have noticed, that temperature is shown wrong.  I have noticed this problem only in the home assistant.
I think that the maximum temperature is 25.6 Celsius and then the home assistant is showing only the difference of this point, as you can see in the picture.

![image](https://user-images.githubusercontent.com/7366491/43887513-efe8660e-9b73-11e8-88f3-a11891e13c86.png)

**Comment by arnili** [comment]
I have the same issue, it's explained here: https://github.com/home-assistant/core/issues/15893#issuecomment-413193363

**Comment by arnili** [comment]
The bug is actually fixed for longer, the commit is here: https://github.com/hackercowboy/python-maxcube-api/commit/ef9294a0d41fdd5dcab7142248ab0d41b8adece1

Currently only die pypi version is outdated which still causes the problem with home-assistant.
