### ISSUE TITLE
only "none" values at "actual_temperature"

### ISSUE THREAD

**Issue by ChristianDannenberg** [hackercowboy/python-maxcube-api#7]
Hello goodfield and big thx for the Api.

I have the folloring issues. When I connected to the cube and will get the actual temperatue of all whith...
---------------------------------
for device in cube.devices:
    if device.type != 1:
        continue
    print(device.name)
    print(device.actual_temperature)
    print(device.target_temperature)
---------------------------------
ThermostatName
None
18.5

Can u help me to geht the actual temperatue ?

thx

Christian

**Comment by oryxcam** [comment]
Similar issue here, but with strange (wrong) temperature values.
---------------------------------------------------
Device: Thermostat Salon
Actual: 2.0
---------------------------------------------------
Device: Thermostat cuisine
Actual: 2.0
---------------------------------------------------
Device: Thermostat bureau
Actual: 0.1
---------------------------------------------------
Device: Thermostat chambre amis
Actual: 23.6
---------------------------------------------------
Device: Thermostat studio
Actual: 24.5
---------------------------------------------------
Device: Thermostat chambre a coucher
Actual: 1.1

**Comment by cs42** [comment]
Temperatures are wrong if the actual temperature **is above 25.5°C** (or 25.6°C)!

**Comment by hackercowboy** [comment]
fixed
